package nl.erasmusmc.bios.euadr.signals;

public class CombineDrugEvent {
    static String[][] drugs = new String[][]{
	{"Allopurinol", "M04AA01"},
	{"Almotriptan", "N02CC05"},
	{"Aluminium", "A02AB"},
	{"Amifostine", "V03AF05"},
	{"Aprepitant", "A04AD12"},
	{"Atazanavir", "J05AE08"},
	{"Azathioprine", "L04AX01"},
	{"Bepridil", "C08EA02"},
	{"BismuthSubsalicylate", "BismuthSubsalicylate"},
	{"Brimonidine", "D11AX21"},
	{"Bromazepam", "N05BA08"},
	{"Caffeine", "N06BC01"},
	{"Carbenicillin", "J01CA03"},
	{"Carboplatin", "L01XA02"},
	{"Cefazolin", "J01DB04"},
	{"Cefotaxime", "J01DD01"},
	{"Chlordiazepoxide", "N05BA02"},
	{"Chlorphenesin", "D01AE07"},
	{"Chlorpromazine", "N05AA01"},
	{"Cilostazol", "B01AC23"},
	{"Clofibrate", "C10AB01"},
	{"Cortisoneacetate", "Cortisoneacetate"},
	{"Desvenlafaxine", "N06AX23"},
	{"Dextroamphetamine", "Dextroamphetamine"},
	{"Dextrothyroxine", "C10AX01"},
	{"Dicumarol", "Dicumarol"},
	{"Digoxin", "C01AA05"},
	{"Dihydroxyaluminium", "Dihydroxyaluminium"},
	{"Divalproexsodium", "Divalproexsodium"},
	{"Dopamine", "C01CA04"},
	{"Doxazosin", "C02CA04"},
	{"Doxepin", "N06AA12"},
	{"Edrophonium", "Edrophonium"},
	{"Eprosartan", "C09CA02"},
	{"Estazolam", "N05CD04"},
	{"Ethinylestradiol", "G03CA01"},
	{"Everolimus", "L01XE10"},
	{"Felodipine", "C08CA02"},
	{"Fenoterol", "R03AC04"},
	{"Fexofenadine", "R06AX26"},
	{"Frovatriptan", "N02CC07"},
	{"Furosemide", "C03CA01"},
	{"Galliumnitrate", "Galliumnitrate"},
	{"Hydrochlorothiazide", "C03AA03"},
	{"Hydrocodone", "R05DA03"},
	{"Isotretinoin", "D10AD04"},
	{"Isradipine", "C08CA03"},
	{"Kava", "Kava"},
	{"Ketazolam", "N05BA10"},
	{"Lapatinib", "L01XE07"},
	{"Levonorgestrel", "G03AC03"},
	{"Melatonin", "N05CH01"},
	{"Meloxicam", "M01AC06"},
	{"Methdilazine", "R06AD04"},
	{"Methohexital", "N01AF01"},
	{"Methyldopa", "C02AB"},
	{"Mexiletine", "C01BB02"},
	{"Midodrine", "C01CA17"},
	{"Mirtazapine", "N06AX11"},
	{"Moricizine", "Moricizine"},
	{"Netilmicin", "J01GB07"},
	{"Nizatidine", "A02BA04"},
	{"Phytonadione", "Phytonadione"},
	{"Pilocarpine", "S01EB01"},
	{"Pipecuronium", "M03AC06"},
	{"Piperacillin", "J01CA12"},
	{"Polythiazide", "C03AA05"},
	{"Propafenone", "C01BC03"},
	{"Propofol", "N01AX10"},
	{"Pseudoephedrine", "R01BA02"},
	{"Pyridostigmine", "N07AA02"},
	{"Quazepam", "N05CD10"},
	{"Quetiapine", "N05AH04"},
	{"Raloxifene", "G03XC01"},
	{"Ranolazine", "C01EB18"},
	{"Ropinirole", "N04BC04"},
	{"Salsalate", "N02BA06"},
	{"Sibutramine", "A08AA10"},
	{"Simvastatin", "C10AA01"},
	{"Streptomycin", "A07AA04"},
	{"Sucralfate", "A02BX02"},
	{"Sufentanil", "N01AH03"},
	{"Sulfamethizole", "B05CA04"},
	{"Sulfasalazine", "A07EC01"},
	{"Sulindac", "M01AB02"},
	{"Sunitinib", "L01XE04"},
	{"Tazobactam", "J01CG02"},
	{"Telithromycin", "J01FA15"},
	{"Tiagabine", "N03AG06"},
	{"Ticlopidine", "B01AC05"},
	{"Tigecycline", "J01AA12"},
	{"Tizanidine", "M03BX02"},
	{"Treprostinil", "B01AC21"},
	{"Triamcinolone", "A01AC01"},
	{"Trimetrexate", "P01AX07"},
	{"Triprolidine", "R06AX07"},
	{"Valsartan", "C09CA03"},
	{"Yohimbine", "G04BE04"},
	{"Zidovudine", "J05AF01"},
	{"Zinc", "A12CB"}
	    };
    
    static String[] events = new String[]{ "liver failure, acute",
	    "drug-induced liver injury",
	    "acute myocardial infarction",
	    "acute renal failure",
	    "anaphylactic shock",
	    "bullous eruptions",
	    "neutropenia",
	    "agranulocytosis",
	    "aplastic anaemia",
	    "pancytopenia",
	    "rhabdomyolysis",
	    "upper gastrointestinal bleeding"};

    public static void main(String[] args) {
	for (int i = 0 ; i < drugs.length ; i++){
	    for (int j = 0 ; j < events.length ; j++){
		System.out.println(drugs[i][0]+"\t" + drugs[i][1] + "\t"+events[j]);
	    }
	}
    }

}
